// <auto-generated />
namespace MTI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class readdreligion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(readdreligion));
        
        string IMigrationMetadata.Id
        {
            get { return "202007300637361_readdreligion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
